### ISSUE TITLE
add sample language for sharing survey

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/WeCountCovid19#11]
Hi friends, in order to “flatten the curve”, we need to know more about what and where COVID-19 symptoms are. Testing is limited, so an online survey has been developed (in Milwaukee!).   

The idea is simple:  If you or a loved one are sick, whether or not you have had any test for COVID-19, please use a phone or computer and go to WeCountCOVID19.com and report symptoms confidentially.  

Would you help to share by passing this message along to your friends and family members?

**Comment by Aycrazy** [comment]
This is a great foundation for sharing about this project.  No edits (or time to edit) at this point on my end :)

**Comment by BarkleyBG** [comment]
needs improvement but we're good for now
