### ISSUE TITLE
Zip-to-MKE neighborhoods

### ISSUE THREAD

**Issue by AntonellaAzzarello** [codeformilwaukee/WeCountCovid19#16]
On the 4/4/2020 call, it was mentioned that neighborhood names may mean more to the community than zip codes. Couple options were discussed (please add if I missed any)

1. Find a online resource that has zip codes to MKE neighborhoods
2. Perhaps a person or persons knows the MKE neighborhoods so well, they may be able to provide this clarification/identification. 
3. [Insert new ideas]

**Comment by AntonellaAzzarello** [comment]
I had initially found this [resource](https://www.zipmap.net/Wisconsin/Milwaukee_County/Milwaukee.htm), but have not previously used it nor validated it.

**Comment by BarkleyBG** [comment]
Nice find!

**Comment by BarkleyBG** [comment]
You may get good feedback if you [join the Milwaukee Slack](https://codeformilwaukee.org/slack) and go to the code-for-mke channel, and then post a question there. I am not sure if other people have looked for this info before.

**Comment by Aycrazy** [comment]
You may find this repo with crosswalks made by our upcoming hack night presenter John Johnson helpful ;) https://github.com/jdjohn215/Milwaukee-Geo-Crosswalks

It's not zips. But census tract level info could be helpful at some pt for your analysis

**Comment by Aycrazy** [comment]
I'm also very confident that I can make you this crosswalk with geopandas or R.  If someone is already taking this on, i'm happy to just coach them through it so they can learn

**Comment by Aycrazy** [comment]
Something you may want to consider is whether you want Zipcode of ZCTAs (Zip Code Tabulated Areas) -- these are meant to be more-or-less standard across time, where as zipcodes change.  They also are meant for easier alignment with census data at the census track or block level.  County ZCTA shapefile can be found here: http://gis-mclio.opendata.arcgis.com/datasets/zip-code-tabulation-areas-zcta

Alternatively, here is the Census Tiger Zip Shapefile from 2017.
https://catalog.data.gov/dataset/tiger-line-shapefile-2017-county-milwaukee-county-wi-topological-faces-polygons-with-all-geocod

**Comment by Aycrazy** [comment]
You can use this [google map](https://www.google.com/maps/d/u/2/edit?mid=10X8oWc4saDdj96yGRtsmjreyf6B5nnoa&ll=43.03094976386615%2C-87.93960640884887&z=12) Wisconsin Voices Made for the census with a zip code layer I added called (zipcodes) to see the relationship between zips and neighborhoods (they don't always align).

Here is a link to ascertain which neighborhoods fall into which zipcodes: https://github.com/Aycrazy/undercounted_map/blob/master/nhood_x_zip.geoJson -- geo json
https://github.com/Aycrazy/undercounted_map/blob/master/nhood_x_zip.zip -- shapefile

**Comment by BarkleyBG** [comment]
assigning to Luke

**Comment by BarkleyBG** [comment]
Closing and moving to #46
