### ISSUE TITLE
Perform initial analysis of responses by zip code

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/WeCountCovid19#20]
Which zip codes have more than 5 responses? 

After we answer this question, can we roll it up to Milwaukee Neighborhood, or other geographical area (as in #4 or #16 )?

After this initial analysis, consider stratifying on whether people report as being sick, or not.

Related to #7. This was the original driving question:
-What geographical areas have the most responses (either "check ins" or "people feelng sick"? (your question) Need to make it clear that this may not be COVID.

**Comment by kalkbren** [comment]
We might need to have larger geographical areas than zip code (because zip code data too sparse).

**Comment by BarkleyBG** [comment]
Good point @kalkbren. We are looking into this for #4 and #16

**Comment by ornekm** [comment]
These are the couple zip code sources that I thought were useful.  They are all originally based on Census numbers after all.
https://data.world/lukewhyte/us-population-by-zip-code-2010-2016
https://simplemaps.com/data/us-zips

**Comment by BarkleyBG** [comment]
migrating to newer issues
