### ISSUE TITLE
Write up a proposal for a basic framework for publishing analysis

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/WeCountCovid19#22]
Charles said he could put together a markup for a Django-based framework. 

I'm looking for things like:
- dependencies
- funding necessary
- basic description of what kinds of analyses we can post
- basic description of how analysts can post new analysis
- how easy is this to upkeep

**Comment by ctcb57** [comment]
Hello everyone, 

Here is my analysis based upon the three primary options which have been presented for the deployment of a website.  Please let me know if you have any questions!

https://docs.google.com/document/d/13TuEWU7BTf2gJs8FkHYv3gHpxklE6httRQ0alkt6V2w/edit?usp=sharing
