### ISSUE TITLE
GitHub training exercise 

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/WeCountCovid19#23]
- [x] Step 1. "clone" the repository so that you have a copy on your desktop
- [x] Step 2. Verify that the latest commit is the same between your local (desktop) copy and the one on the website
- [x] Step 3. We want to add some spanish language help to the readme. You can edit a file directly from your browser. Go to the [main page](https://github.com/codeformilwaukee/WeCountCovid19) and scroll down to the readme, and then click the edit pencil in the top-right to bring up a markdown file that you can edit. 
- [x] Step 4. After you make the changes in step 3., verify that the main page shows your most recent commit
- [x] step 5. Back to your laptop: Verify that your laptop does not yet have this most recent commit. This means that your copy is out-of-date and needs to sync
- [x] Step 6. Sync your local copy with the web version (aka cloud version aka 'origin) by bringing up your local GitHub client and clicking "fetch origin" in the top right.

---
step 3 : language to add

Please add this language above https://github.com/codeformilwaukee/WeCountCovid19#questions in a section (with two hashes ##) called "En Espanol"

¿Se siente enfermo? Indique sus síntomas en la encuesta confidencial aún si no se le han hecho la prueba para diagnosticar el coronavirus. Su experiencia cuenta. ¡Ud. cuenta! Disponible en inglés y español.

WeCountCOVID19.com
University of Wisconsin-Milwaukee, Joseph J. Zilber School of Public Health

**Comment by leah-hoogstra** [comment]
added. I included the bottom two lines (info about the Zilber School of Public Health) at the very end of the README document
