### ISSUE TITLE
Links to Journalism & Media we've been showcased in

### ISSUE THREAD

**Issue by JordanSiem** [codeformilwaukee/WeCountCovid19#29]
Hey All,

Lets use this issue to share journalism and media posts. These articles could be used to share on social media sites and will help us build credibility.

Here are a couple articles I found so far:

https://spectrumnews1.com/wi/milwaukee/coronavirus/2020/04/08/new-wisconsin-study-tracks-people-with-coronavirus-symptoms

https://uwm.edu/news/feeling-sick-uwm-launches-project-to-better-track-spread-of-covid-19-2/

https://www.jsonline.com/story/news/2020/04/09/coronavirus-wisconsin-latest-updates-cases-cancellations/5120462002/

**Comment by BarkleyBG** [comment]
https://www.wuwm.com/post/covid-19-symptom-tracking-can-be-early-warning-system-says-uwm-epidemiologist#stream/0

**Comment by kalkbren** [comment]
Here is one more - a radio interview on "Lake Effect" - 

https://www.wuwm.com/post/tuesday-lake-effect-april-election-covid-19-online-survey-milwaukee-day-eye-health

**Comment by BarkleyBG** [comment]
Thanks for settig this up @JordanSiem . I have moved it to the trello board so the web dev team can put it up once they get there https://trello.com/c/9JwzDNik
