### ISSUE TITLE
Route survey-takers to another helpful page afterwards

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/WeCountCovid19#5]
After survey respondents finish the survey, they may want to see any of the following things. We should provide a splash page with relevant links on it.

- the analysis of the data
- CDC or MKE Health information
- financial resources
- ?

**Comment by kalkbren** [comment]
Great ideas!

**Comment by kalkbren** [comment]
I edited the "end" page of the survey just now.  It does not include all info Brian mentions above, but I did add a link to the CDC symptom checker for people wanting help determining whether they should seek medical care.

**Comment by BarkleyBG** [comment]
closing this and moving it to trello
